extends Node

## Canonical 70-stage progression carried over from ALSAEQA.
const STAGES := {
    1: {"id":"chains_in_the_mine", "title":"Chains in the Mine", "next":2},
    2: {"id":"the_hidden_mark", "title":"The Hidden Mark", "next":3},
    3: {"id":"echo_under_stone", "title":"Echo Under Stone", "next":4},
    4: {"id":"broken_lift", "title":"Broken Lift", "next":5},
    5: {"id":"the_captives_trail", "title":"The Captive’s Trail", "next":6},
    6: {"id":"forest_of_whispers", "title":"Forest of Whispers", "next":7},
    7: {"id":"the_old_shrine", "title":"The Old Shrine", "next":8},
    8: {"id":"beast_at_the_pass", "title":"Beast at the Pass", "next":9},
    9: {"id":"storm_on_the_ridge", "title":"Storm on the Ridge", "next":10},
    10: {"id":"the_storm_thread", "title":"The Storm Thread", "next":11},
    11: {"id":"hunter_of_the_mist", "title":"Hunter of the Mist", "next":12},
    12: {"id":"living_mountain", "title":"Living Mountain", "next":13},
    13: {"id":"chain_of_the_colossus", "title":"Chain of the Colossus", "next":14},
    14: {"id":"storm_within", "title":"Storm Within", "next":15},
    15: {"id":"fallen_city", "title":"Fallen City", "next":16},
    16: {"id":"companions_secret", "title":"Companion’s Secret", "next":17},
    17: {"id":"black_desert", "title":"Black Desert", "next":18},
    18: {"id":"frozen_kingdom", "title":"Frozen Kingdom", "next":19},
    19: {"id":"echo_of_ancestors", "title":"Echo of Ancestors", "next":20},
    20: {"id":"land_of_giants", "title":"Land of Giants", "next":21},
    21: {"id":"ashes_of_old_road", "title":"Ashes of the Old Road", "next":22},
    22: {"id":"silent_prison", "title":"The Silent Prison", "next":23},
    23: {"id":"broken_seal", "title":"The Broken Seal", "next":24},
    24: {"id":"before_the_truth", "title":"Before the Truth", "next":25},
    25: {"id":"first_confirmed_trace", "title":"First Confirmed Trace", "next":26},
    26: {"id":"abandoned_caravan", "title":"Abandoned Caravan", "next":27},
    27: {"id":"broken_symbol", "title":"Broken Symbol", "next":28},
    28: {"id":"hidden_witness", "title":"Hidden Witness", "next":29},
    29: {"id":"prison_record", "title":"Prison Record", "next":30},
    30: {"id":"split_paths", "title":"The Split Paths", "next":31},
    31: {"id":"hidden_refuge", "title":"Hidden Refuge", "next":32},
    32: {"id":"survivor_message", "title":"Survivor Message", "next":33},
    33: {"id":"enemy_network", "title":"Enemy Network", "next":34},
    34: {"id":"mountain_road", "title":"Mountain Road", "next":35},
    35: {"id":"false_grave", "title":"False Grave", "next":36},
    36: {"id":"second_caravan", "title":"Second Caravan", "next":37},
    37: {"id":"survivor_road", "title":"Survivor Road", "next":38},
    38: {"id":"family_stronghold", "title":"Family Stronghold", "next":39},
    39: {"id":"the_separation", "title":"The Separation", "next":40},
    40: {"id":"the_family", "title":"The Family", "next":41},
    41: {"id":"two_histories", "title":"Two Histories", "next":42},
    42: {"id":"empty_crest", "title":"The Empty Crest", "next":43},
    43: {"id":"blood_in_archive", "title":"Blood in the Archive", "next":44},
    44: {"id":"road_of_heirs", "title":"Road of the Heirs", "next":45},
    45: {"id":"first_creature_traces", "title":"First Creature Traces", "next":46},
    46: {"id":"trust", "title":"Trust", "next":47},
    47: {"id":"first_tame", "title":"First Tame", "next":48},
    48: {"id":"first_ride", "title":"First Ride", "next":49},
    49: {"id":"rough_terrain", "title":"Rough Terrain", "next":50},
    50: {"id":"the_chase", "title":"The Chase", "next":51},
    51: {"id":"rescue_by_mount", "title":"Rescue by Mount", "next":52},
    52: {"id":"side_route", "title":"Side Route", "next":53},
    53: {"id":"trust_test", "title":"Trust Test", "next":54},
    54: {"id":"companion_rides", "title":"Companion Rides", "next":55},
    55: {"id":"great_route", "title":"Great Route", "next":56},
    56: {"id":"storm_tracks", "title":"Storm Tracks", "next":57},
    57: {"id":"heart_of_storm", "title":"Heart of the Storm", "next":58},
    58: {"id":"ancient_herd", "title":"Ancient Herd", "next":59},
    59: {"id":"the_bond", "title":"The Bond", "next":60},
    60: {"id":"lightning_dash", "title":"Lightning Dash", "next":61},
    61: {"id":"thunder_roar", "title":"Thunder Roar", "next":62},
    62: {"id":"lightning_kick", "title":"Lightning Kick", "next":63},
    63: {"id":"storm_charge", "title":"Storm Charge", "next":64},
    64: {"id":"lightning_crossing", "title":"Lightning Crossing", "next":65},
    65: {"id":"storm_leap", "title":"Storm Leap", "next":66},
    66: {"id":"lightning_shield", "title":"Lightning Shield", "next":67},
    67: {"id":"storm_summon", "title":"Storm Summon", "next":68},
    68: {"id":"thunder_sense", "title":"Thunder Sense", "next":69},
    69: {"id":"storm_mode", "title":"Storm Mode", "next":70},
    70: {"id":"heirs_of_storm", "title":"Heirs of the Storm", "next":0}
}

func get_stage(stage_number: int) -> Dictionary:
    return STAGES.get(stage_number, {})

func is_valid_stage(stage_number: int) -> bool:
    return STAGES.has(stage_number)
